#!/usr/bin/env bash

# Kill any process running on port 80
sudo kill $(sudo lsof -t -i :80)

# Ensure Nginx is listening on port 80 of all the server's active IPv4 IPs
sudo sed -i 's/# listen 80 default_server;/listen 80 default_server;/g' /etc/nginx/sites-enabled/default
sudo sed -i 's/# listen \[::\]:80 default_server;/listen \[::\]:80 default_server;/g' /etc/nginx/sites-enabled/default
sudo sed -i 's/# worker_processes/auto;/g' /etc/nginx/nginx.conf

# Restart Nginx
sudo systemctl restart nginx

